### ISSUE TITLE
The class of coco_skeleton

### ISSUE THREAD

**Issue by Kismetzc** [svolokh/MocapToFbx#2]
I want to use the coco_skeleton. But it seems that its class is incomplete compared to the other two.

**Comment by svolokh** [comment]
Hi, please note (as stated in the README) that this part of the code was derived from the video2bvh repository: https://github.com/KevinLTT/video2bvh. so I can’t give any insight into why this part of the code may be incomplete.

**Comment by Kismetzc** [comment]
OK THX

**Comment by Kismetzc** [comment]
Hi,@svolokh
I can't contact the author of video2bvh, so I have to try to ask for your help.
I really don't understand the code [here](https://github.com/HW140701/VideoTo3dPoseAndBvh/blob/d7bc5f76c90602096ca6377b0fae53c29383d7b7/bvh_skeleton/cmu_skeleton.py#L199). 
Like why the direction of x_dir is the subtraction of these two nodes (maybe be child nodes), why some nodes use ZXY, but others use XYZ, is there any difference in the DCM matrix obtained in this way?
